version: "3"
services:
    project-builder:
        image: ambassador4ik/dotnet-solution-restore
        volumes:
            - ${INPUT_DIR}:/input/
            - ${BUILDER_OUTPUT_DIR}:/output/

    qodana:
        image: jetbrains/qodana-dotnet
        volumes:
            - ${BUILDER_OUTPUT_DIR}:/data/project/
            - ${QODANA_OUTPUT_DIR}:/data/results/
        command:
            - --save-report
        depends_on:
            project-builder:
                condition: service_completed_successfully

    compiler:
        image: ambassador4ik/dotnet-compiler
        volumes:
            - ${BUILDER_OUTPUT_DIR}:/input/
            - ${COMPILER_OUTPUT_DIR}:/output/
        depends_on:
            project-builder:
                condition: service_completed_successfully

    checker:
        image: ambassador4ik/dotnet-checker
        volumes:
            - ${COMPILER_OUTPUT_DIR}:/compiler-output/
            - ${TESTS_INPUT_DIR}:/input/
            - ${CHECKER_OUTPUT_DIR}:/output/
        depends_on:
            compiler:
                condition: service_completed_successfully
